// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MigratePackagesConfigToPackageReferencesExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMigratePackagesConfigToPackageReferencesExtensionString = "4b43db1a-e109-4fd4-83a9-4e41f8bb44b3";
        public static Guid guidMigratePackagesConfigToPackageReferencesExtension = new Guid(guidMigratePackagesConfigToPackageReferencesExtensionString);

        public const string guidMigratePackagesConfigToPackageReferencesExtensionCmdSetString = "a1a90506-4ca0-4a18-a0f7-386e40eeffc2";
        public static Guid guidMigratePackagesConfigToPackageReferencesExtensionCmdSet = new Guid(guidMigratePackagesConfigToPackageReferencesExtensionCmdSetString);

        public const string guidMigratePackagesConfigToPackageReferencesExtensionUIRuleString = "f2fbecb3-4a80-4a31-83aa-0e1fffcf8563";
        public static Guid guidMigratePackagesConfigToPackageReferencesExtensionUIRule = new Guid(guidMigratePackagesConfigToPackageReferencesExtensionUIRuleString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MigratePackagesConfigToPackageReferencesMenuGroup = 0x0001;
        public const int MigratePackagesConfigToPackageReferencesCommand = 0x0100;
    }
}